/* AUTHENTICATION */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const USER_TYPE_NORMAL = 'USER_TYPE_NORMAL';
export const USER_TYPE_MANAGER = 'USER_TYPE_MANAGER';
export const USER_TYPE_SUPER = 'USER_TYPE_SUPER';
